apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: namespace
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ${NAME}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}-sa
      namespace: ${NAME}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ${NAME}-sa-role
      namespace: ${NAME}
    rules:
      - apiGroups: [ '*' ]
        resources: [ '*' ]
        verbs: [ '*' ]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}-sa-rolebinding
      namespace: ${NAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: ${NAME}-sa-role
    subjects:
      - namespace: ${NAME}
        kind: ServiceAccount
        name: ${NAME}-sa
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: ${NAME}-sa-cluster-role
      namespace: ${NAME}
    rules:
      - apiGroups: [ "" ]
        resources: [ "pods", "pods/log", "namespaces" ]
        verbs: [ "get", "watch", "list" ]
      - apiGroups: [ "extensions", "apps" ]
        resources: [ "deployments" ]
        verbs: [ "get", "list", "watch" ]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: ${NAME}-sa-cluster-rolebinding
      namespace: ${NAME}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}-sa
        namespace: ${NAME}
    roleRef:
      kind: ClusterRole
      name: ${NAME}-sa-cluster-role
      apiGroup: rbac.authorization.k8s.io
parameters:
  - name: NAME
    value: mk-e2e-tests
